about: >
	This file describes all the numeric parameters for modeling and standardization. All values 
	are assumed to be floats unless otherwise specified, and have the given range and precision values.

	Each IOU has its own set of parameters